# Generated by Django 4.0.5 on 2022-06-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_receita_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
    ]
